set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d'm

set -sg escape-time 10
set -g history-limit 10000
set -g mouse on
set -g set-clipboard on

unbind C-b
set -g prefix `
bind-key ` send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind %
unbind '"'

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Done :D"

bind-key -n 'M-t' display-popup -E -w 80% -h 80% "$SHELL"
bind-key -n 'C-n' display-popup -E "bash -i -c 'read -p \"session name: \" name; tmux new-session -d -s \"\$name\" && tmux switch-client -t \"\$name\"'"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind -n M-s set-option -g status

set-window-option -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# ===== Colored ======
# thm_bg="#222222"
# thm_fg="#ECEFF4"

# thm_red="#BF616A"
# thm_peach="#D08770"
# thm_yellow="#EBCB8B"
# thm_green="#A3BE8C"
# thm_teal="#8FBCBB"
# thm_blue="#88C0D0"
# thm_violet="#B48EAD"

# thm_subtext_1="#E5E9F0"
# thm_subtext_0="#D8DEE9"
# thm_overlay_1="#4C566A"
# thm_surface_1="#434C5E"
# thm_surface_0="#3B4252"
# thm_mantle="#2E3440"
# thm_crust="#2E3440"


# ========= Black & White =========== 
thm_bg="#1c1c1c"
thm_fg="#e0e0e0"

thm_red="#666666"
thm_peach="#7a7a7a"
thm_yellow="#999999"
thm_green="#858585"
thm_teal="#b5b5b5"
thm_blue="#cccccc"
thm_violet="#e0e0e0"

thm_subtext_1="#b5b5b5"
thm_subtext_0="#cccccc"
thm_overlay_1="#525252"
thm_surface_1="#383838"
thm_surface_0="#262626"
thm_mantle="#1c1c1c"
thm_crust="#141414"



set -g status "on"
set -g status-interval 1
set -g status-justify left
set -g status-style "bg=${thm_bg},fg=${thm_fg}"

set -g status-left-length 30
set -g status-left "#[fg=${thm_bg},bg=${thm_blue},bold] #S #[default] "

set -g window-status-separator " "
set -g window-status-format "#[fg=${thm_subtext_1},bg=${thm_surface_0}] #I:#W "
set -g window-status-current-format "#[fg=${thm_bg},bg=${thm_yellow},bold] #I:#W "

set -g status-right-length 100
set -g status-right "#{?client_prefix,#[fg=${thm_bg}]#[bg=${thm_red}]#[bold] PREFIX #[default] ,}#[fg=${thm_subtext_0},bg=${thm_surface_0}] #P #[fg=${thm_fg}]#{pane_current_command} #[fg=${thm_bg},bg=${thm_teal},bold] %H:%M "
set -g popup-border-style "fg=${thm_blue}"
set -g popup-border-lines "rounded"

# Pane borders
set -g pane-border-style "fg=${thm_surface_0}"
set -g pane-active-border-style "fg=${thm_blue}"
